### ISSUE TITLE
Use the latest version of sae_vis

### ISSUE THREAD

**Issue by jordansauce** [ApolloResearch/e2e_sae#54]
Currently our feature dashboards rely on an old commit of Callum McDougall's [sae_vis ](https://github.com/callummcdougall/sae_vis) library. Specifically,  [callummcdougall/sae_vis@b28a0f7](https://github.com/callummcdougall/sae_vis/commit/b28a0f7c7e936f4bea05528d952dfcd438533cce), before he changed many of the data storing classes I was relying on with the subsequent commit. It would be nice to update our code to be compatible with the latest version of sae_vis. 

This could also be accomplished in a more future-proof way by submitting a pull request adding something like our SAE-class-agnostic functions `parse_activation_data()` and `parse_prompt_data()` to sae_vis, so that we don't have to independently maintain them.

**Comment by danbraunai-apollo** [comment]
Linked to #58.
